-- MySQL Script generated by MySQL Workbench
-- Sun May  2 19:43:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation_game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_generation_game_online` ;

-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_classe` (
  `id_aldeia` INT NOT NULL AUTO_INCREMENT,
  `elemento` VARCHAR(20) NOT NULL,
  `Orixá` VARCHAR(20) NOT NULL,
  `nome_aldeia` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_aldeia`),
  UNIQUE INDEX `id_aldeia_UNIQUE` (`id_aldeia` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_personagem` (
  `id_personagem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `arma` VARCHAR(20) NOT NULL,
  `aldeia` VARCHAR(20) NOT NULL,
  `ataque` INT NOT NULL,
  `defesa` INT NOT NULL,
  `fk_aldeia` INT NOT NULL,
  PRIMARY KEY (`id_personagem`, `fk_aldeia`),
  UNIQUE INDEX `category_id_UNIQUE` (`id_personagem` ASC) VISIBLE,
  INDEX `fk_tb_personagem_tb_classe_idx` (`fk_aldeia` ASC) VISIBLE,
  CONSTRAINT `fk_tb_personagem_tb_classe`
    FOREIGN KEY (`fk_aldeia`)
    REFERENCES `db_generation_game_online`.`tb_classe` (`id_aldeia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
